=begin
#Geocoding and Search API v7

#This document describes the Geocoding and Search API.

The version of the OpenAPI document: 7.83

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

# Common files
require 'here_geocoding_search/api_client'
require 'here_geocoding_search/api_error'
require 'here_geocoding_search/version'
require 'here_geocoding_search/configuration'

# Models
require 'here_geocoding_search/models/access_response_coordinate'
require 'here_geocoding_search/models/address'
require 'here_geocoding_search/models/autocomplete_result_item'
require 'here_geocoding_search/models/autosuggest_entity_result_item'
require 'here_geocoding_search/models/autosuggest_query_result_item'
require 'here_geocoding_search/models/browse_result_item'
require 'here_geocoding_search/models/category'
require 'here_geocoding_search/models/chain'
require 'here_geocoding_search/models/contact'
require 'here_geocoding_search/models/contact_information'
require 'here_geocoding_search/models/country_info'
require 'here_geocoding_search/models/display_response_coordinate'
require 'here_geocoding_search/models/error_response'
require 'here_geocoding_search/models/ev_charging_attributes'
require 'here_geocoding_search/models/ev_charging_point'
require 'here_geocoding_search/models/ev_connector'
require 'here_geocoding_search/models/ev_name_id'
require 'here_geocoding_search/models/extended_attribute'
require 'here_geocoding_search/models/field_score'
require 'here_geocoding_search/models/geocode_result_item'
require 'here_geocoding_search/models/lookup_response'
require 'here_geocoding_search/models/map_view'
require 'here_geocoding_search/models/match_info'
require 'here_geocoding_search/models/onebox_search_result_item'
require 'here_geocoding_search/models/open_search_autocomplete_response'
require 'here_geocoding_search/models/open_search_autosuggest_response'
require 'here_geocoding_search/models/open_search_browse_response'
require 'here_geocoding_search/models/open_search_geocode_response'
require 'here_geocoding_search/models/open_search_reverse_geocode_response'
require 'here_geocoding_search/models/open_search_search_response'
require 'here_geocoding_search/models/opening_hours'
require 'here_geocoding_search/models/parsing'
require 'here_geocoding_search/models/phoneme'
require 'here_geocoding_search/models/phonemes_section'
require 'here_geocoding_search/models/query_term_result_item'
require 'here_geocoding_search/models/range'
require 'here_geocoding_search/models/reverse_geocode_result_item'
require 'here_geocoding_search/models/scoring'
require 'here_geocoding_search/models/street_info'
require 'here_geocoding_search/models/structured_opening_hours'
require 'here_geocoding_search/models/supplier'
require 'here_geocoding_search/models/supplier_reference'
require 'here_geocoding_search/models/time_zone_info'
require 'here_geocoding_search/models/title_and_address_highlighting'
require 'here_geocoding_search/models/title_highlighting'

# APIs
require 'here_geocoding_search/api/default_api'

module HereGeocodingSearch
  class << self
    # Customize default settings for the SDK using block.
    #   HereGeocodingSearch.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
