=begin
#Geocoding and Search API v7

#This document describes the Geocoding and Search API.

The version of the OpenAPI document: 7.83

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for HereClient::EvChargingAttributes
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe HereClient::EvChargingAttributes do
  let(:instance) { HereClient::EvChargingAttributes.new }

  describe 'test an instance of EvChargingAttributes' do
    it 'should create an instance of EvChargingAttributes' do
      expect(instance).to be_instance_of(HereClient::EvChargingAttributes)
    end
  end
  describe 'test attribute "connectors"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "total_number_of_connectors"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
