=begin
#Geocoding and Search API v7

#This document describes the Geocoding and Search API.

The version of the OpenAPI document: 7.83

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for HereClient::OpenSearchAutocompleteResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe HereClient::OpenSearchAutocompleteResponse do
  let(:instance) { HereClient::OpenSearchAutocompleteResponse.new }

  describe 'test an instance of OpenSearchAutocompleteResponse' do
    it 'should create an instance of OpenSearchAutocompleteResponse' do
      expect(instance).to be_instance_of(HereClient::OpenSearchAutocompleteResponse)
    end
  end
  describe 'test attribute "items"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
